In [106]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import TimeSeriesSplit
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
from sklearn.preprocessing import Imputer
from sklearn import preprocessing
from sklearn import utils
from sklearn.metrics import mean_squared_error
#import pyramid as pm

# matplotlib.use('agg')
excel_file = "/Users/BrandtLawson/Desktop/Combined_Values.csv"
Combined_Values = pd.read_csv(excel_file)
#spCommData = pd.read_csv(r"comSP.csv")

#plotting individual columns
#Combined_Values.plot(kind='scatter',x='Date',y='Close',color='red')
# # plt.show()
# #Combined_Values.plot(kind='scatter',x='Date',y='GDP',color='blue')
# # plt.show()
# Combined_Values.plot(kind='scatter',x='Date',y='USD_to_EUR',color='green')
# # plt.show()
# Combined_Values.plot(kind='scatter',x='Date',y='NonFarm_Payroll',color='yellow')
# # plt.show()
# Combined_Values.plot(kind='scatter',x='Date',y='3_month_Libor',color='orange')
# # plt.show()
# Combined_Values.plot(kind='scatter',x='Date',y='Unemployment',color='purple')
# plt.show()

#getting data in a range where we have data from all columns
Combined_Values = Combined_Values.drop(Combined_Values.index[0:9]) #gets rid of first N/A
Combined_Values = Combined_Values.drop(Combined_Values.index[1000:17989]) #gets rid of last N/A
Combined_Values.index = pd.DatetimeIndex(end=pd.datetime.today(), periods=len(Combined_Values), freq='1D')
#y.index = pd.DatetimeIndex(end=pd.datetime.today(), periods=len(df), freq='d')
#x.index = pd.DatetimeIndex(end=pd.datetime.today(), periods=len(df), freq='1D')
#print(Combined_Values.head())

#plt.clf()
#ax = plt.gca()
# Combined_Values.plot(kind='scatter',x='Date',y='Close',color='red', ax=ax)
# Combined_Values.plot(kind='scatter',x='Date',y='GDP',color='blue',ax=ax)
# Combined_Values.plot(kind='scatter',x='Date',y='USD_to_EUR',color='green',ax=ax)
# Combined_Values.plot(kind="scatter", x='Date', y='NonFarm_Payroll', color='yellow', ax=ax)
# Combined_Values.plot(kind='scatter',x='Date',y='3_month_Libor',color='orange',ax=ax)
# Combined_Values.plot(kind='scatter',x='Date',y='Unemployment',color='purple',ax=ax)

A = Combined_Values.values
A = A[::-1] #this is needed to reverse the order of the data so that the oldest data is read and plotted first!
y = A[:, 5]
print(type(y))
print(y.shape)
#print("y" + str(y))
y = y.reshape(-1,1)
#print(A[:,8])
x = A[:,[7, 8, 9, 10, 11]]
x = x.reshape(-1,5)
print(x.shape)
# print(type(y))     #we want numpy.ndaray
# print(y.shape)     #we want dimensions 1000x1
                        


#prediction_space = np.linspace(min(x),max(x)).reshape(-1, 1)
# plt.scatter(x, y, color='blue')
# plt.plot(prediction_space, reg.predict(prediction_space),color='black', linewidth=3)
# plt.show()
print("+++++++++++++++ single var ols++++++++++++++++++++++++++++++++++")

#print("\nNo Split R^2 " + str(reg.score(x, y)))
#print("\nNo Split R^2 different scoring"+ str(mean_squared_error(y,reg.fit(x,y).predict(x))))
# cv_results = cross_val_score(reg, x, y, cv=5, scoring='r2')




<class 'numpy.ndarray'>
(1000,)
(1000, 5)
+++++++++++++++ single var ols++++++++++++++++++++++++++++++++++


In [152]:
index = 1
numberPossibleFeatures = 5
answerMatrix=[]
iter = 0
for a in range(2):
    for b in range(2):
        for c in range(2):
            for d in range(2):
                for e in range(2):
                    if a+b+c+d+e != 0:
                        print(str(index) + " a" + str(a) + "b" + str(b) + "c" + str(c) + "d" + str(d) + "e" + str(e) )
                        binaryArray = [a,b,c,d,e]
                        print(binaryArray)
                        individualMatrix = []
                        while(iter < numberPossibleFeatures):
                            print(iter)
                            if binaryArray[iter] == 1:
                                individualMatrix.append(x[:,iter].reshape(-1, 1))
                            iter+=1
                        
                        
                        iter = 0
                        index+=1
                        
                        #individualMatrix = individualMatrix.reshape(-1,2)
                        for i in range(a+b+c+d+e): #printing the head of the column
                            print(individualMatrix[i][0][0])
                        
                        NIM = np.array(individualMatrix)
                        NIM2 = np.squeeze(NIM)
                        print(type(NIM))
                        NIM2 = np.transpose(NIM2)
                        if a+b+c+d+e == 1:
                            NIM2 = np.reshape(NIM2, (-1,1))
                        print(NIM2.shape)
                            
#                         newarray = np.array(individualMatrix)
#                         print(newarray[0][i])
                        
                        reg = linear_model.LinearRegression()
                        reg.fit(NIM2,y)
                        print(reg.coef_)
                        #x = A[:,[8, 10]]
                        #x = x.reshape(-1,2)
                        #print(" " + str(x[0, :]))
                        #reg = linear_model.LinearRegression()
                        #reg.fit(x,y)
                        answerList = [0] * 5   #[0][0][0][0][0]
                        iter2 = 0
                        coefNum = 0
                        while (iter2 < numberPossibleFeatures):
                            if binaryArray[iter2] ==1:
                                answerList[iter2] = reg.coef_[0][coefNum]
                                #print(iter2)
                                #print(type(reg.coef_))
                                coefNum+=1
                            iter2+=1        
                        print(answerList)
                        answerMatrix.append(answerList)
                       
                        #print("coefft GDP=" + str(reg.coef_))
print(answerMatrix)
                        

1 a0b0c0d0e1
[0, 0, 0, 0, 1]
0
1
2
3
4
8962.0
<class 'numpy.ndarray'>
(1000, 1)
[[-0.24682267]]
[0, 0, 0, 0, -0.24682266538898742]
2 a0b0c0d1e0
[0, 0, 0, 1, 0]
0
1
2
3
4
0.2346
<class 'numpy.ndarray'>
(1000, 1)
[[388.87557836]]
[0, 0, 0, 388.87557835559494, 0]
3 a0b0c0d1e1
[0, 0, 0, 1, 1]
0
1
2
3
4
0.2346
8962.0
<class 'numpy.ndarray'>
(1000, 2)
[[ 3.84684469e+02 -3.92271337e-03]]
[0, 0, 0, 384.68446880297523, -0.003922713374939354]
4 a0b0c1d0e0
[0, 0, 1, 0, 0]
0
1
2
3
4
139812.0
<class 'numpy.ndarray'>
(1000, 1)
[[0.0803225]]
[0, 0, 0.08032249959027943, 0, 0]
5 a0b0c1d0e1
[0, 0, 1, 0, 1]
0
1
2
3
4
139812.0
8962.0
<class 'numpy.ndarray'>
(1000, 2)
[[ 0.07782577 -0.00901729]]
[0, 0, 0.07782577353667175, 0, -0.009017289891502885]
6 a0b0c1d1e0
[0, 0, 1, 1, 0]
0
1
2
3
4
139812.0
0.2346
<class 'numpy.ndarray'>
(1000, 2)
[[5.67771045e-03 3.67330991e+02]]
[0, 0, 0.005677710453196125, 367.33099067962354, 0]
7 a0b0c1d1e1
[0, 0, 1, 1, 1]
0
1
2
3
4
139812.0
0.2346
8962.0
<class 'numpy.ndarray'>
(